### ISSUE TITLE
Meeting Links to not go directly to meeting

### ISSUE THREAD

**Issue by glenjarvis** [BayPiggies/pelican_website#50]
When one visits the https://baypiggies.net/ website, and then clicks on "Meetings," one will get a list of meetings (https://baypiggies.net/category/meetings.html).

However, when one of the meetings are selected, that meeting in question is not loaded. For example, when selecting the "Thursday, July 25th, 2019 Meeting," the current meeting (the index.html meeting) is displayed (i.e,  https://baypiggies.net/ ). What is expected to be shown is  http://baypiggies.net/meeting-2019-07-25.html. 

This is happening for all meetings selected. This also reproduces locally (and not just at https://baypiggies.net/).

**Comment by aldudko** [comment]
This happens not for all, but for all past meetings that contain the keyword `:url:` in their rst files.

**Comment by glenjarvis** [comment]
@o0-o0  (Alex), Thank you!!!  @bdbaddog (Bill)  I saw this `:url:` key without a value in the past. I can easily make a PR and update those for us to check if this resolves the problem. That way, @bdbaddog , all you have to do is *merge* if you are happy with it.

@bdbaddog Are you okay if I make that branch for you?

**Comment by aldudko** [comment]
I'm not sure whether removing it completely is the right solution (still reading up the docs).
But if this is the correct solution, could you remove it from README.md too, so that no one copy-pastes it from there.

- https://github.com/BayPiggies/pelican_website/blame/master/README.md#L46
- https://github.com/BayPiggies/pelican_website/blame/master/README.md#L46

**Comment by glenjarvis** [comment]
@o0-o0 👍

**Comment by bdbaddog** [comment]
Fixed.
